### ISSUE TITLE
Unresponsive in Ubuntu 18.04

### ISSUE THREAD

**Issue by tops91** [dave-theunsub/clamtk-gnome#13]
Hello! I have installed ClamTk in Ubuntu 18.04. It opens but does not respond: nothing happens when I click on any of the buttons, e.g., Settings, History, Update, etc. Thinking that adding ClamTk-Gnome may help, I installed it but there was no change. I did use ClamTk in some earlier version of Ubuntu 2/3 years ago and there was no such problem at the time. Would really appreciate your help. Thanks in advance.

**Comment by dave-theunsub** [comment]
Hi,

Did you double-click the items?  Try that.  If you want single-click, go into the settings and change that option. I'll actually be removing the double-click thing in the next version.

respectfully
Dave M

**Comment by tops91** [comment]
Double-click works. Many thanks.
Regards!

**Comment by dave-theunsub** [comment]
Thanks for the update.  Closing for now.
