### ISSUE TITLE
not working on Fedora 30

### ISSUE THREAD

**Issue by egcp** [dave-theunsub/clamtk-gnome#14]
Hi, The right click to check individual files or folder is not working on Fedora 30. The option does not even appear on the list when right clicking. It worked well in Fedora 29. Any idea of what is going on? Thanks.
clamtk-6.01-1.fc30.noarch
clamtk-gnome-0.03-1.fc.noarch
nautilus-python-1.2.3-1.fc30.x86_64

**Comment by dave-theunsub** [comment]
Hi @egcp ,

I'll check more into it when I get home.

In the meanwhile, has it ever worked with Fedora 30 for you? Or is this pretty new?

There's another (but likely different) issue I'm going to fix mentioned here: https://gitlab.com/dave_m/clamtk/issues/83 . Might be related, but maybe not since you're saying it's not showing up as an option.

I'll investigate. Thanks for reporting!

respectfully,
Dave M

**Comment by egcp** [comment]
Thanks Dave! It never worked on Fedora 30. It showed the menu option fine in Fedora 29, but since I updated to 30 (not a clean reinstall), it has never shown it again. I run Gnome in Wayland.

**Comment by egcp** [comment]
Thanks Dave! The menu option showed fine in Fedora 29, but since I updated to Fedora 30 (not a clean reinstall) it does not show. This is a pretty vanilla installation of Fedora, so I do not have other file managers installed, only Files (v 3.32.3). The other issue you highlighted is not related since I right clicked on many different files and folders with no accented characters. I run Gnome on Wayland.

**Comment by dave-theunsub** [comment]
Hi @egcp ,

Can you open a terminal window and type "nautilus" (no quotes)? See if any error messages show up in the terminal window as the file manager opens. That might shed some light on this.

respectfully,
Dave M

**Comment by egcp** [comment]
Hi Dave, This is what I get. I hope is helpful. 
----------
$ nautilus
Initializing clamtk-gnome
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/clamtk-gnome.py", line 64, in get_file_items
    tip=_('Scan %s for threats...') % file.get_name(),
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'

**Comment by dave-theunsub** [comment]
Thanks @egcp , that's useful! Give us a little to examine it.

respectfully,
Dave M

**Comment by SunyataZero** [comment]
Hi all! I think i've found the problem, looking at [the changeset for Fedora 30](https://fedoraproject.org/wiki/Releases/30/ChangeSet#Migrate_Python-based_Nautilus_extensions_to_Python_3) i found this:

> The Python backend for the nautilus-python extension will be updated from python2 to python3. All Nautilus extensions written in Python will need to be checked for Python 3 compatibility and updated if necessary. Extensions compatible only with Python 2 will no longer be supported.

In short i think this is "on me" because i was the one who wrote the Python 3 code. I'm going to look into how to fix this

Kind Regards, Sunyata

**Comment by SunyataZero** [comment]
@egcp Can i ask: Which method for installing clamtk-gnome did you use? Reference: [readme.md](https://gitlab.com/dave_m/clamtk-gnome/blob/master/README.md)

**Comment by dave-theunsub** [comment]
@SunyataZero ,

It might be that all we have to do is change line 64 to:

`tip=_('Scan %s for threats...') % file.get_name().decode(),`  

Still works on CentOS but I don't have a Fedora with me. I can check it later.

respectfully,  
Dave M

**Comment by egcp** [comment]
> @egcp Can i ask: Which method for installing clamtk-gnome did you use? Reference: [readme.md](https://gitlab.com/dave_m/clamtk-gnome/blob/master/README.md)

I apologize, I did not see this question. 
I installed it using "sudo dnf install clamtk-gnome", which I had downloaded from your site because it was not in Fedora's depository.

**Comment by egcp** [comment]
It works ib CentOS because they are still using python2 there.

**Comment by egcp** [comment]
I just noticed that it shows on nautilus, but wrongly formatted (no icon just " 'bScan directory for theats...'  " (that funny 'b) if I right click on a directory on the topbar, but only there.

**Comment by SunyataZero** [comment]
> Still works on CentOS but I don't have a Fedora with me. I can check it later.

@dave-theunsub I only run Ubuntu myself so if you could i'd be grateful! Alternatively i could install Fedora on a virtual machine on my main computer

**Comment by SunyataZero** [comment]
> I installed it using "sudo dnf install clamtk-gnome", which I had downloaded from your site because it was not in Fedora's depository.

@egcp I'm confused and i'd like to understand so i can help you: dnf is Fedora's packaging tool right? What file did you download and from which site? (Please give a link to the file you used)

The reason i asked about how you installed the plugin is that i wanted to make sure that you are using the latest version

**Comment by SunyataZero** [comment]
> TypeError: %b requires a bytes-like object, or an object that implements bytes, not 'str'

I don't think i wrote this line, do you know what this means @dave-theunsub ? It seems strange that the tooltip is expected to be something other than a string right?

**Comment by egcp** [comment]
dnf in Fedora 30 or RPM Fusion could not find clamtk-gnome (probably because of python2 deprecation). So, I went on the web and found clamtk-gnome-0.03-1.fc.noarch and installed it. As said above, that  worked fine in Fedora 29, but not any more in Fedora 30. In my first comment are the versions of the programs that I am using. Interestingly enough, the changelog  for clamtk-gnome says:

0.03 - 20190412
---------------
    * Allow for python3.

Thanks!

**Comment by dave-theunsub** [comment]
@SunyataZero , there is a similar discussion [here](https://stackoverflow.com/questions/33054527/typeerror-a-bytes-like-object-is-required-not-str-when-writing-to-a-file-in).

respectfully,  
Dave M

**Comment by SunyataZero** [comment]
> It might be that all we have to do is change line 64 to:
> 
> tip=_('Scan %s for threats...') % file.get_name().decode(),
> 
> Still works on CentOS but I don't have a Fedora with me. I can check it later.

@dave-theunsub Hi, have you had a chance to try this out?

> there is a similar discussion here.

Okay, i have read this and yes it seems that `decode` might work!

**Comment by dave-theunsub** [comment]
It's not even showing up in F31 - as in not even an option. I'll keep investigating.

**Comment by dave-theunsub** [comment]
Hi @egcp ,

I think it's fixed now with v0.04. Please let me know how it works.
The Fedora and Debian builds are 0.04 for Python3, while CentOS is still 0.03.

https://gitlab.com/dave_m/clamtk/-/wikis/Downloads

respectfully,
Dave M

**Comment by egcp** [comment]
Hi,
Thanks Dave. With the new version of clamtk-gnome (v. 0.04), the right click option on files and directories now works in Fedora 30 and 31. Though I noticed that if your right click on a directory it does not scan the directory recursively (no scanning of directories under the directory first selected for scanning). I do not know if that is by design. Just FYI. Thanks again.

**Comment by dave-theunsub** [comment]
Hi @egcp ,

Thank you for confirming it works.

Regarding the recursive scanning, do you have it selected in the Settings?

respectfully,
Dave M

**Comment by egcp** [comment]
My mistake, I did not have it selected in settings within ClamTK. Working fine. Thanks for all your work on it.
