### ISSUE TITLE
Problem with filenames with spaces in nautilus

### ISSUE THREAD

**Issue by j-licht** [dave-theunsub/clamtk-gnome#15]
When I star the checking form the right click menu in nautilus with a filename that contains spaces, I ended up with the start screen and not a scan report.
Remove the quote, solves the problem for me:
https://github.com/dave-theunsub/clamtk-gnome/blob/3c0711e3c87ef804c6445e3c7e972fcb3b923bed/clamtk-gnome.py#L51

**Comment by dave-theunsub** [comment]
Hi @j-licht ,

Thank you for letting me know. I'll look into it. If it's that simple I can push a fix this weekend.

respectfully,  
Dave M

**Comment by dave-theunsub** [comment]
Hi @j-licht ,

[0.05](https://gitlab.com/dave_m/clamtk/-/wikis/Downloads) has been released. Works for me! :)

Thanks again for reporting it.

respectfully,
Dave M

**Comment by j-licht** [comment]
Thanks, works for me too. :+1:
